[package]
name = "lungyam-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
async-trait = "0.1"
lungyam-core = { path = "../lungyam-core" }
pingora = { version = "0.8.0", features = ["proxy"] }

[lints]
workspace = true
